---
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: docker
  loop:
    - "{{ clickhouse_compose_dir }}"
    - "{{ clickhouse_data_dir }}"
    - "{{ clickhouse_log_dir }}"

- name: Template Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ clickhouse_compose_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart ClickHouse

- name: Start ClickHouse
  command: docker compose up -d
  args:
    chdir: "{{ clickhouse_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
