---
- name: Mount EBS data disk
  include_tasks: ../../base/common/tasks/mount_disk.yml
  vars:
    target_mount_dir: "{{ clickhouse_data_dir }}"
    mount_owner: "ubuntu"
    mount_group: "docker"
    mount_mode: "0777"

- name: Create Compose and Log Directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: ubuntu
    group: docker
  loop:
    - { path: "{{ clickhouse_compose_dir }}", mode: "0755" }
    - { path: "{{ clickhouse_log_dir }}", mode: "0777" }
    - { path: "{{ clickhouse_data_dir }}", mode: "0777" }

- name: Template Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ clickhouse_compose_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart ClickHouse

- name: Start ClickHouse
  command: docker compose up -d
  args:
    chdir: "{{ clickhouse_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
