---
# Image
grafana_version: "10.4.1"
prometheus_version: "v2.51.0"

# Network
grafana_port: 3000
prometheus_port: 9090

# Credentials
grafana_admin_user: "admin"
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') | default('grafana_prod_secret_pass', true) }}"

# Paths
grafana_data_dir: "/opt/airpay/grafana/data"
grafana_compose_dir: "/opt/airpay/grafana"
prometheus_data_dir: "/opt/airpay/grafana/prometheus_data"
