---
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: docker
  loop:
    - "{{ scylla_compose_dir }}"
    - "{{ scylla_data_dir }}"

- name: Template Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ scylla_compose_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Scylla

- name: Start Scylla
  command: docker compose up -d
  args:
    chdir: "{{ scylla_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
