---
- name: Mount EBS data disk
  include_tasks: ../../base/common/tasks/mount_disk.yml
  vars:
    target_mount_dir: "{{ grafana_data_dir }}"
    mount_owner: "472"
    mount_group: "472"

- name: Create Observability Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: docker
  loop:
    - "{{ grafana_compose_dir }}"
    - "{{ grafana_compose_dir }}/provisioning/datasources"
    - "{{ grafana_compose_dir }}/provisioning/dashboards"
    - "{{ grafana_compose_dir }}/provisioning/dashboards/json"
    - "{{ grafana_compose_dir }}/targets"

- name: Ensure Grafana Data Directory Permissions
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: '0755'
    owner: "472"
    group: "472"

- name: Ensure Prometheus Data Directory Permissions
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    mode: '0755'
    owner: "65534"
    group: "65534"

- name: Template Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ grafana_compose_dir }}/prometheus.yml"
    mode: '0644'
  notify:
    - Reload Prometheus
    - Restart Prometheus

- name: Template Grafana Datasources
  template:
    src: datasources.yaml.j2
    dest: "{{ grafana_compose_dir }}/provisioning/datasources/datasources.yaml"
    mode: '0644'

- name: Template Grafana Dashboards Provider
  template:
    src: dashboards.yaml.j2
    dest: "{{ grafana_compose_dir }}/provisioning/dashboards/dashboards.yaml"
    mode: '0644'

- name: Copy Grafana Dashboards
  copy:
    src: "{{ item }}"
    dest: "{{ grafana_compose_dir }}/provisioning/dashboards/json/{{ item }}"
    mode: '0644'
  loop:
    - dashboard-server-monitoring.json
    - dashboard-database-services.json
    - dashboard-apisix-gateway.json


- name: Template Compose

  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_compose_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Grafana

- name: Start Grafana & Prometheus
  command: docker compose up -d
  args:
    chdir: "{{ grafana_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
