# ==========================================
# Airpay Prod Environment Inventory
# ==========================================

# --- DATABASES ---
[aerospike_nodes]
# x.x.x.x

[clickhouse_nodes]
10.0.31.119
10.0.32.78
10.0.33.218
[scylladb_nodes]
10.0.21.25
10.0.22.89
10.0.23.46
[yugabytedb_nodes]
10.0.41.178
10.0.42.198
10.0.43.58
[databases:children]
aerospike_nodes
clickhouse_nodes
scylladb_nodes
yugabytedb_nodes

# --- CACHE ---
[redis_nodes]
# x.x.x.x

[cache:children]
redis_nodes

# --- MESSAGING ---
[rabbitmq_nodes]
# x.x.x.x

[messaging:children]
rabbitmq_nodes

# --- ORCHESTRATION ---
[temporal_nodes]
# x.x.x.x

[orchestration:children]
temporal_nodes

# --- IAM ---
[keycloak_nodes]
# x.x.x.x

[iam:children]
keycloak_nodes

# --- SECURITY ---
[infisical_nodes]
# x.x.x.x

[security:children]
infisical_nodes

# --- NETWORKING ---
[apisix_nodes]
# x.x.x.x

[networking:children]
apisix_nodes

# --- OBSERVABILITY ---
[grafana_nodes]
10.0.51.41
[observability:children]
grafana_nodes

# ==========================================
# META GROUP: ALL NODES
# ==========================================
[airpay_nodes:children]
databases
cache
messaging
orchestration
iam
security
networking
observability
