---
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: docker
  loop:
    - "{{ temporal_compose_dir }}"
    - "{{ temporal_data_dir }}"
    - "{{ temporal_data_dir }}/postgres"

- name: Template Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ temporal_compose_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Temporal

- name: Start Temporal
  command: docker compose up -d
  args:
    chdir: "{{ temporal_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"
