---
- name: Mount EBS data disk
  include_tasks: ../../base/common/tasks/mount_disk.yml
  vars:
    target_mount_dir: "{{ yugabyte_data_dir }}"
    mount_owner: "ubuntu"
    mount_group: "docker"

- name: Create Compose Directory
  file:
    path: "{{ yugabyte_compose_dir }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: docker

- name: Template Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ yugabyte_compose_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start Yugabyte
  command: docker compose up -d
  args:
    chdir: "{{ yugabyte_compose_dir }}"
  register: compose_output
  changed_when: "'Started' in compose_output.stdout or 'Created' in compose_output.stdout"

- name: Wait for Yugabyte to be ready
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ yugabyte_port_tserver_web }}"
    delay: 10
    timeout: 240
