---
# Security Group Vars (DEV)

# INFISICAL
infisical_version: "latest"
infisical_port: 8089
infisical_port_db: 5434
infisical_db_user: "infisical"
infisical_db_pass: "infisical_db_dev_password"
infisical_db_name: "infisical"
infisical_auth_secret: "YOUR_AUTH_SECRET_KEY_DEV_ENVIRONMENT_ONLY"
infisical_encryption_key: "YOUR_ENCRYPTION_KEY_DEV_ENVIRONMENT_ONLY"
infisical_data_dir: "/opt/airpay/infisical/data"
infisical_compose_dir: "/opt/airpay/infisical"
